### PR TITLE
Non-root user support in Scorpio containers

### PR DESCRIPTION
**Pull request by swathichittajallu**
Commits for this PR include:
1) Non-root user container support for Scorpio services - Entity Manager, Info Server, Query Manager, Subscription Manager, History Manager, Registry Manager.
2) Non-root user container support for Spring Cloud services - Gateway, Eureka, Config Server.

### CODE REVIEW

**Review by wagmarcel — CHANGES_REQUESTED** [review]
@swathichittajallu  please squash the two commits into one single one and provide the description in the commit message. e.g.
-------------------------------------------------
Restrict privileges on Scorpio containers

Commits for this PR include:
Non-root user container support for Scorpio services - Entity Manager, Info Server, Query Manager, Subscription Manager, History Manager, Registry Manager.
Non-root user container support for Spring Cloud services - Gateway, Eureka, Config Server.

See also: #10
-------------------------------------------------------

Then force push the commit to your branch. The commit looks good content-wise.

**Review by wagmarcel — APPROVED** [review]

**Review by sysarcher — COMMENTED** [review]
more important than the `docker build` command is to make sure that the runtime `uid` is not `root`

I think the `docker build` command doesn't help here with security at least.

@wagmarcel is this what your [original request](https://github.com/IndustryFusion/ScorpioBroker/pull/3#pullrequestreview-825827716) was?

I think in addition (or without changes to) the Dockerfiles, we need to make sure runtime manifests ensure non-privileged user is used. Can someone point me there?

**Comment by swathichittajallu** [comment]
@sysarcher non-root user restriction is provided at both Docker and Pod levels.  Ref: https://github.com/IndustryFusion/DigitalTwin/pull/61/commits/f720ff40f12215d09dac4866137b407704d70eb4

**Review by sysarcher — APPROVED** [review]
LGTM

**Pull request merged**
